package hbi.core.demo.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "company")
public class Company extends BaseDTO {

     public static final String FIELD_COMPANY_ID = "companyId";
     public static final String FIELD_COM_NAME = "comName";
     public static final String FIELD_COM_ADDR = "comAddr";
     public static final String FIELD_COM_TYPE = "comType";


     @Id
     @GeneratedValue
     private Long companyId;

     @Length(max = 64)
     private String comName;

     @Length(max = 64)
     private String comAddr;

     @Length(max = 16)
     private String comType;


     public void setCompanyId(Long companyId){
         this.companyId = companyId;
     }

     public Long getCompanyId(){
         return companyId;
     }

     public void setComName(String comName){
         this.comName = comName;
     }

     public String getComName(){
         return comName;
     }

     public void setComAddr(String comAddr){
         this.comAddr = comAddr;
     }

     public String getComAddr(){
         return comAddr;
     }

     public void setComType(String comType){
         this.comType = comType;
     }

     public String getComType(){
         return comType;
     }

     }
