package hbi.core.demo.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "employee")
public class Employee extends BaseDTO {

     public static final String FIELD_EMPLOYEE_ID = "employeeId";
     public static final String FIELD_COMPANY_ID = "companyId";
     public static final String FIELD_NAME = "name";
     public static final String FIELD_AGE = "age";
     public static final String FIELD_SEX = "sex";


     @Id
     @GeneratedValue
     private Long employeeId;

     private Long companyId;

     @Length(max = 32)
     private String name;

     private Long age;

     @Length(max = 16)
     private String sex;

     @Transient
     private String cname;

    public String getCname() {
        return cname;
    }

    public Employee setCame(String cname) {
        this.cname = cname;
        return this;
    }

    public void setEmployeeId(Long employeeId){
         this.employeeId = employeeId;
     }

     public Long getEmployeeId(){
         return employeeId;
     }

     public void setCompanyId(Long companyId){
         this.companyId = companyId;
     }

     public Long getCompanyId(){
         return companyId;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setAge(Long age){
         this.age = age;
     }

     public Long getAge(){
         return age;
     }

     public void setSex(String sex){
         this.sex = sex;
     }

     public String getSex(){
         return sex;
     }

     }
